language: generic
sudo: required
services:
- docker
before_install:
- openssl -aes-256-cbc -K $encrypted_d1cb78e5cc9c_key -iv $encrypted_d1cb78e5cc9c_iv
  -in travis_rsa.enc -out .\\travis_rsa -d
  - eval "$(ssh-agent -s)"
  - chmod 600 travis_rsa
  - ssh-add travis_rsa
- docker build -t mikeaws1/docker_tutorial -f Dockerfile.dev .
- docker push mikeaws1/dtutorial mikeaws1/docker_tutorial
script:
- docker run -e CI=true mikeaws1/docker_tutorial npm run test -- --coverage
deploy:
  provider: digitalocean
  region: ''
  app:
  evn:
  bucket_name:
  on:
    branch: master
