language: generic
sudo: required
services:
- docker
before_install:
- openssl aes-256-cbc -K $encrypted_0ddd2445e49f_key -iv $encrypted_0ddd2445e49f_iv
  -in travis_rsa.enc -out travis_rsa -d
- eval "$(ssh-agent -s)"
- chmod 600 travis_rsa
- ssh-add travis_rsa
- docker build -t mikeaws1/docker_tutorial -f Dockerfile.dev .
- docker login --username mikeaws1 --password ${DOCKER_HUB}
- docker push mikeaws1/docker_tutorial
script:
- docker run -e CI=true mikeaws1/docker_tutorial npm run test -- --coverage
#release:
  	#echo ${DOCKER_PASSWORD} | docker login -u ${DOCKER_USERNAME} --password-stdin
  	#docker push dockerhub-user/my-app:${VERSION}
	  #VERSION=${VERSION} 
#    ./deploy.sh


deploy:
  provider: script
  region: us-west-1
  script: deploy.sh
  on:
    branch: master