version: '3'
services: 
  web:
    environment: 
      - CHOKIDAR_USEPOLLING=true
    image: mikeaws1/docker_tutorial
    build: 
      context: .
      dockerfile: Dockerfile
    ports: 
      - "3000:3000"
    volumes:
      - /app/node_modules
      - .:/app
  tests:
    environment: 
      - CHOKIDAR_USEPOLLING=true
    build: 
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - /app/node_modules
      - .:/app
    command: ["npm", "run", "test"]